#!/bin/bash

n=5000
span=$n
mss=50
ec2=10000
fanout=25

reps=10

echo method reps n m mss ec1 ec2 span
for ec2 in 2000 4000 6000 8000 10000 12000 14000 16000 18000 20000 ; do
	m=$(( fanout * n ))
	ec1=$(( mss * fanout * ec2 ))
	echo shortPath $reps $n $m $mss $ec1 $ec2 $span
	maxFloRep shortPath $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*shortPath' <run_temp
	grep '^\[.*findpath' <run_temp
done

echo method reps n m mss ec1 ec2 span
for ec2 in 2000 4000 6000 8000 10000 12000 14000 16000 18000 20000 ; do
	m=$(( fanout * n ))
	ec1=$(( mss * fanout * ec2 ))
	echo maxCap $reps $n $m $mss $ec1 $ec2 $span
	maxFloRep maxCap $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*maxCap' <run_temp
	grep '^\[.*findpath' <run_temp
done

echo method reps n m mss ec1 ec2 span
for ec2 in 2000 4000 6000 8000 10000 12000 14000 16000 18000 20000 ; do
	m=$(( fanout * n ))
	ec1=$(( mss * fanout * ec2 ))
	echo scale $reps $n $m $mss $ec1 $ec2 $span
	maxFloRep scale $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*scale' <run_temp
	grep '^\[.*findpath' <run_temp
done

