#!/bin/bash

n=4000
span=$n
mss=100
ec1=100000000
ec2=10000000

reps=10

echo shortPath
for m in 20000 40000 60000 80000 100000 ; do
	maxFloRep shortPath $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*shortPath' <run_temp
	grep '^\[.*findpath' <run_temp
done

echo maxCap
for m in 20000 40000 60000 80000 100000 ; do
	maxFloRep maxCap $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*maxCap' <run_temp
	grep '^\[.*findpath' <run_temp
done

echo scale
for m in 20000 40000 60000 80000 100000 ; do
	maxFloRep scale $reps $n $m $mss $ec1 $ec2 $span
	gprof maxFloRep.exe >run_temp 
	grep '^\[.*scale' <run_temp
	grep '^\[.*findpath' <run_temp
done

