#! /bin/sh
# Run a Monitor for a forest network
#
# usage: CliMgrScript dir xip hip rip hfa rfa tlim
#
# dir is the directory in which to run fHost
# xip is this host's externally visible IP address
# hip is this host's IP address in the forest network
# rip is the IP address of the host's router
# hfa is this host's forest address
# rip is the forest address of the host's router
# comt is the comtree number on which the avatar sends
# and receives data packets
# tlim is the number of seconds to run
# tag is an integer tag used to identify logging files
#
# The script assumes that the directory in which
# the script is run contains log and err subdirectories.
# The logging output is placed in the file log/m,
# The standard error output is sent to err/m.
#
# The forest host is run in the background, so the
# script returns immediately.
#
cd $1
CliMgr $2 $3 $4 $5 $6 $7 $8 $9 ${10} >log/cm 2>err/cm &
