#!/bin/bash

p=.5
reps=1
w=1000

for n in 500 600 700 800 900 1000 1250 1500 1750 2000 2500 3000; do
	echo faltPath $n
	matchRep faltPath $reps $n $p $w $n
	gprof matchRep.exe >run_temp 
	grep '^\[.*faltPathC::faltPathC' <run_temp
	echo floSz $n
	matchRep floSz $reps $n $p $w $n
	gprof matchRep.exe >run_temp 
	grep '^\[.*floSz' <run_temp
done
