#!/bin/bash

n=1000
seed=1

echo bsDinic 100
for p in .05 .1 .2 .4 ; do
	echo $p
	bsDinic2 100 $n $p $seed
	gprof bsDinic2.exe >run_temp 
	grep '^\[.*bsDinic' <run_temp
	grep '^\[.*dinic' <run_temp
	grep '^\[.*findpath' <run_temp
done
