#! /bin/sh
# Run a Monitor for a forest network
#
# usage: MonScript dir xip hip rip hfa rfa ccfa gridSize tlim
#
# dir is the directory in which to run fHost
# xip is this host's externally visible IP address
# hip is this host's IP address in the forest network
# rip is the IP address of the host's router
# hfa is this host's forest address
# rfa is the forest address of the host's router
# ccfa is the forest address of the comtree controller
# gridSize is number of squares in x and y dimensions
# tlim is the number of seconds to run
#
# The script assumes that the directory in which
# the script is run contains log and err subdirectories.
# The logging output is placed in the file log/m,
# The standard error output is sent to err/m.
#
# The forest host is run in the background, so the
# script returns immediately.
#
cd $1
Monitor $2 $3 $4 $5 $6 $7 $8 $9 >log/m 2>err/m &
