#! /bin/sh
# Run a forest avatar
#
# usage: fAvatar dir hip rip hfa rfa comt tlim tag
#
# dir is the directory in which to run fHost
# hip is this host's IP address in the forest network
# rip is the IP address of the host's router
# hfa is this host's forest address
# rip is the forest address of the host's router
# comt is the comtree number on which the avatar sends
# and receives data packets
# tlim is the number of seconds to run
# tag is an integer tag used to identify logging files
#
# The script assumes that the directory in which
# the script is run contains log and err subdirectories.
# The logging output is placed in the file log/ai,
# where i is the value of the tag argument.
# The standard error output is sent to err/ai.
#
# The forest host is run in the background, so the
# script returns immediately.
#
cd $1
fAvatar $2 $3 $4 $5 $6 $7 >log/a${8} 2>err/a${8} &
