#! /bin/sh
# Run a Network Manager for a forest network
#
# usage: NmScript dir xip hip rip hfa rfa tlim clientInfo
#
# dir is the directory in which to run fNetMgr
# xip is this host's externally visible IP address
# hip is this host's IP address in the forest network
# rip is the IP address of the host's router
# hfa is this host's forest address
# rfa is the forest address of the host's router
# tlim is the number of seconds to run
# clientInfo is a file of information about clients
#
# The script assumes that the directory in which
# the script is run contains log and err subdirectories.
# The logging output is placed in the file log/m,
# The standard error output is sent to err/m.
#
# The forest host is run in the background, so the
# script returns immediately.
#
cd $1
NetMgr $2 $3 $4 $5 >log/nm 2>err/nm &
